### ISSUE TITLE
Text comes with weird format

### ISSUE THREAD

**Issue by fassko** [fassko/Dodies.lv#119]
![36242377_10155972094484877_7844225989063213056_n](https://user-images.githubusercontent.com/29482/41958085-a5c3c08a-79f1-11e8-8415-e51a18b89b9d.jpg)

**Comment by trakais** [comment]
Mans CMS liek daudzpunkti (&hellip;), kad apgriež tekstu, lai izvadītu saīsināto variantu. Skatos, ka šeit tāds nav: https://dodies.lv/lv/obj/zanas-likloci.html?json=1

Taču laikam tāds ir lielajā JSON failā. Es apgriežu teksu līdz noteiktam limitam, kad lielajā kartē jāattēlo info kastītes. Ja gribi attēlot visu tekstu, vari lietot individuālos JSON, bet ja gribi paturēt saīsināto, būtu pareizi jāattēlo &hellip; kā "..." vai arī tā vietā jārāda links uz mājaslapu un pilno tekstu. Kā vēlies.

**Comment by trakais** [comment]
(man patīk ka Github komentāros tas HELLIP aizstājas ar ..., tāpēc mans komentārs tāds dīvains sanāca :)

**Comment by fassko** [comment]
Skaidrs, mēģināšu tad izmantot description no linka struktūras, ko devi. Tad gan vajadzēs savest kārtībā EN linkus galvenajā JSON failā.

**Comment by trakais** [comment]
Vajadzētu būt labotam tagad 


 ---- On Thu, 28 Jun 2018 09:33:44 +0300 Kristaps Grinbergs <notifications@github.com> wrote ----

**Comment by fassko** [comment]
@trakais 
Šim, piemēram, description nāk ar &quot; kas ir " simbols. Vai to varēsi labot savā pusē?

https://dodies.lv/lv/obj/zakumuias-dabas-taka.html?json=1

**Comment by trakais** [comment]
Izskatās, ka tā notiek, ja man CMS saglabātajā tekstā ir jebkāda veida pēdiņas, viņš tās pārtaisa par tiem QUOT entitijiem. Es šeit konkrēti vienkārši no teksta izņēmu pēdiņas, bet, ja kaut kur ir vēl, tad tur būs tas pats. Nevaru apsolīt, ka nekad tekstā nelikšu nekādas pēdiņas. 


 ---- On Sun, 01 Jul 2018 18:46:56 +0300 Kristaps Grinbergs <notifications@github.com> wrote ----

**Comment by fassko** [comment]
Drošības pēc es dekodēšu šīs HTML entities.
