### ISSUE TITLE
Jauni GEOJSON faili

### ISSUE THREAD

**Issue by trakais** [fassko/Dodies.lv#125]
Turpmāk objektus sadalam trijās kategorijās, atsevišķos failos. Faila struktūra šobrīd paliek tāda pati. 

nosaukuma princips {valoda}{objekts}.geojson, piemēram: 

 'lvtaka.geojson'
 'lvpikniks.geojson'
 'lvtornis.geojson'

Web kartē standartā aktīvas tikai takas, ar vienkāršu iespēju ieslēgt arī pārējos objektus. Kaut kā līdzīgi būtu forši arī aplikācijā.

**Comment by trakais** [comment]
na = name
ti = tips
st = statuss
km = garums
txt = apraksts
dat = datums 
img = mazā bilde, kvadrātiska 690x690
img2 = lielā bilde
url = relatīvs links uz aprakstu

**txt** (apraksts) ir sakodēts base64, 
bet **na** (name) vajadzētu transformēt, lai nav entities (tur ir &#039; un tamlīdzīgi).

**Comment by trakais** [comment]
Tu laikam joprojām lieto vecos failus? Kartē vārdiem ir html entities tur, kur jābūt LV burtiem. Domāju, vai šo aizverot neatrisinātos problēma.

**Comment by fassko** [comment]
Neko neesmu mainījis. Droši vien tiek izmantoti vēl vecie.

**Comment by fassko** [comment]
Papētīju, ka šim mazliet darba jāiegulda, jo pašlaik atjaunojot datus visi vecie tiek izdzēsti. Tagad sanāk izdzēst konkrētu tipu. Tas nozīmē refaktorēt lejupielādes un atjaunošanas funkcionalitāti mazliet universiālāk ar konkrētu tipu.

**Comment by fassko** [comment]
Atradu, kā šo atrisināt diezgan fiksi, izmantojot PromiseKit.

Bet problēma, ir, ka vecos failus nevar dzēst ārā, jo ne visi cilvēki atjauno aplikācijas.
Risinājums varētu būt redirekts uz takas failu.

**Comment by fassko** [comment]
Šis ir implementēts. 1.10.0 versijā būs pieejams.
