### ISSUE TITLE
HTML tagus jāfiltrē ārā no īsajiem tekstiem

### ISSUE THREAD

**Issue by trakais** [fassko/Dodies.lv#26]
Valguma baskāju takai nezkāpēc mazajā aprakstā ir izmantoti HTML bold tegi. Es varētu no tā izvairīties, taču varētu tos kaut kā filtrēt ārā pirms rādīt.

**Comment by fassko** [comment]
Ērtāk būtu, ja savā pusē izfiltrētu.

**Comment by trakais** [comment]
OK, nav problēmu, vari aizvērt šo
