### ISSUE TITLE
Show photo in the info page

### ISSUE THREAD

**Issue by trakais** [fassko/Dodies.lv#29]
Vajadzētu iegrābt bildīti un rādīt apraksta lapā, kādi būtu pareizie izmēri kādos gatavot bildes? Pieņemu, ka esošie ir par sīku? 

Bildes ir te: http://dodies.lv/img/plancu.jpg (/img/{id}.jpg)

**Comment by fassko** [comment]
es ieviesu nelielu kārtību bilžu nosaukumos. tagad visām takām, kurām ir apraksti (to tu itkā zini) var ņemt bildi pēc principa:

http://dodies.lv/img/large/{{ID}}-01.jpg

bilde ir 1012px plata. tev tur ir Google Analytics, ja kādam objektam trūkst faila, to jau tu redzēsi, ja? Tad es varēšu to labot, jo bilžu man reāli ir vairāk kā vajag, tikai ne vienmēr esmu tās ielicis.
