### ISSUE TITLE
iPad initial zoom too far

### ISSUE THREAD

**Issue by trakais** [fassko/Dodies.lv#33]
**Problem**: Big screens center the map strangely, and initial zoom is too far from Latvia. 

[Problem cause](https://github.com/fassko/Dodies.lv/blob/f2532a2b7a7eab1a23181f02a07a1bd6612a31ea/Dodies.lv/Map.swift#L42)

**Solution 1** (complicated): try to use GPS coordinates as the CLLocationCoordinate2D and set zoom to 8 (no idea what happens if there is no GPS? fallback to Riga?)

**Solution 2** (simple): center on Riga like this:

`mapView.setCenterCoordinate(CLLocationCoordinate2D(latitude: 56.9296, longitude: 24.1014), zoomLevel: 8, animated: false)`

![ccfwi98waaaoosz](https://cloud.githubusercontent.com/assets/5909887/13332185/7f435980-dc09-11e5-8a41-6ce42951a877.jpg)

**Comment by fassko** [comment]
Solved to set NE and SW coordinates to fit Latvia.
