### ISSUE TITLE
Garš apraksts atveras skrollēts līdz lejai

### ISSUE THREAD

**Issue by trakais** [fassko/Dodies.lv#43]
Ja apraksts ir garāks kā ietilpst fiksētajā "rāmī", aprakstu var skrollēt (kas patiesībā nav gluži intuitīvi). Apraksts ir skrollējies līdz apakšai pēc defaulta. Nezinu vai tas rāmis vispār ir labs risinājums, bet katrā ziņā teksts vismaz varēja sākties no sākuma: 

![photo 27-02-16 21 03 19](https://cloud.githubusercontent.com/assets/5909887/13374738/e895a93c-dd95-11e5-9649-63205eb4cede.png)

**Comment by trakais** [comment]
Klau, ideja, kā būtu ar šāda tipa pieeju atpakaļ uz karti tikšanai? Atbrīvojas vieta, alignments sakārtots. 
![dizains](https://cloud.githubusercontent.com/assets/5909887/13374808/c5b9bece-dd97-11e5-9b95-c037f5bb082f.png)

**Comment by fassko** [comment]
Man ir doma šo pārtaisīt, lai tas "izstiepjas", jo esošais variants nav OK uz maziem ekrāniem.

#47
