### ISSUE TITLE
jauns json formāts

### ISSUE THREAD

**Issue by trakais** [fassko/Dodies.lv#66]
JSON pārveidots lai aizņemtu mazāk vietas, tagad pati dodies.lv karte to izmanto, turklāt fails ģenerējas no datubāzes, nekāds CSV vairs netiek lietots. JSON faili ir vairāki, šobrīd ir latviski un angliski. 

Lauki:

name: nosaukums
tips: taka, tornis, parks, pikniks
st: parbaudits, neparbaudits (statuss slikts eksistē tikai daubāzē, JSONā netiek rakstīts)
km: kilometri (decimālais separators punkts_
txt: apraksts
dat: apsekošanas datums formātā YYYY-MM-DD
img: mazā bilde (izmantojas tikai saitā)
img2: lielā bilde (izmantosies saitā un aplikācijā)
url: relatīvais links uz pilno aprakstu

un koordinātes

faili atrodami:

http://dodies.lv/json/lv.geojson
http://dodies.lv/json/en.geojson

piemērs failam "http://dodies.lv/json/lv.geojson":

```
{  
   "type":"FeatureCollection",
   "features":[  
      {  
         "type":"Feature",
         "properties":{  
            "name":"Tilderu dabas taka",
            "tips":"taka",
            "st":"parbaudits",
            "km":"0.7",
            "txt":"Neliela dabas taka gar Gauju, pa ceļam vairāki koka tilti, trepes. Var redzēt dolomīta ieguves vietas. Takas beigās augstas trepes noved lejā pie Gaujas, taču tur ir visai aizaudzis un atpūtas vietas nav.",
            "dat":"2016-05-21",
            "img":"http://dodies.lv/couch/uploads/image/takas/tilderu-600x400.jpg",
            "img2":"http://dodies.lv/couch/uploads/image/takas/tilderu.jpg",
            "url":"/lv/tilderu-taka"
         },
         "geometry":{  
            "type":"Point",
            "coordinates":[  
               26.34319,
               57.45440
            ]
         }
      },
```

**Comment by trakais** [comment]
Es tikai īsti neesmu drošs cik lielu bildi vajag aplikācijai.

img parasti ir 600px plats
img2 parasti ir lielāks 

Var jau vienmēr lietot to mazo, tad es to nelikšu JSON failā un tas paliks stipri mazāks

**Comment by fassko** [comment]
@trakais kā ir ar http://dodies.lv/apraksti/lastchanged.txt ? Vai tas tiks atjaunots?

**Comment by trakais** [comment]
Jā uztaisīšu lai turpina atjaunoties

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.11.24&pv=9.3.1&source=email_footer_2]
On Sat, Jun 18, 2016 at 16:10, Kristaps Grinbergs <notifications@github.com> wrote:
@trakais [https://github.com/trakais] kā ir ar http://dodies.lv/apraksti/lastchanged.txt [http://dodies.lv/apraksti/lastchanged.txt] ? Vai tas tiks atjaunots?

**Comment by fassko** [comment]
@trakais es domāju, ka izmantosim tikai mazo bildi, respektīvi **img**

**Comment by trakais** [comment]
Šķiet ka skrips izlabots, tagad glabā jaunā lv.geojson izmaiņu laiku.
Esmu mežā, salaboju no iPhone ar kaut kādu SSH programmu :)
N.
Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.11.24&pv=9.3.1&source=email_footer_2]
On Sat, Jun 18, 2016 at 16:11, Normunds Rustanovičs <trakais@gmail.com> wrote:
Jā uztaisīšu lai turpina atjaunoties

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.11.24&pv=9.3.1&source=email_footer_2]
On Sat, Jun 18, 2016 at 16:10, Kristaps Grinbergs <notifications@github.com> wrote:
@trakais [https://github.com/trakais] kā ir ar http://dodies.lv/apraksti/lastchanged.txt [http://dodies.lv/apraksti/lastchanged.txt] ? Vai tas tiks atjaunots?

**Comment by fassko** [comment]
Paldies, notestē aplikāciju un ja viss ir OK, es izlaidīšu jauno versiju.

Veiksmi atpūtā.

K.

**Comment by trakais** [comment]
Izskatās, ka krešo uzreiz pēc logo, karte neparādās. Json ?

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.11.24&pv=9.3.1&source=email_footer_2]
On Sun, Jun 19, 2016 at 16:38, Kristaps Grinbergs <notifications@github.com> wrote:
Paldies, notestē aplikāciju un ja viss ir OK, es izlaidīšu jauno versiju.

Veiksmi atpūtā.

K.

**Comment by fassko** [comment]
Saprotu, kas par vainu. Jāizdomā, kā upgreidot iekšējo datu bāzi starp versijām.

Došu ziņu, kad salabošu.

K.
